apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web
  name: web-svc
spec:
  ports:
  - name: 5000-30080
    nodePort: 30080
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    io.kompose.service: web
  type: NodePort
